### ISSUE TITLE
Implement Upgrades and Powerups

### ISSUE THREAD

**Issue by steamroller-airmash** [steamroller-airmash/airmash-server#14]
This encompasses several different requirements:

- [x] Ensure that all existing systems are upgrade-aware
- [x] Implement upgrade dropping mechanism
- [x] Make existing systems handle shields
- [x] Determine missile offsets for infernos (#4)
- [x] Write powerup spawning code (#57)
   - [ ] specialize for CTF
      - [x] Base shields for CTF (#84)
   - [ ] specialize for FFA
- [x] make players spawn with initial shield
- [x] add systems to deal with shield expiry
