### ISSUE TITLE
Metaissue for bugs found in QA testing

### ISSUE THREAD

**Issue by steamroller-airmash** [steamroller-airmash/airmash-server#19]
After having a bunch of people on the server, we found a lot of bugs! This issue will list them all in order to have a place to track all the related issues.

- [x] Destroyed by/killed message is delayed by 1 (#20)
- [x] (CTF) If both flags are being carried and one team caps, then the other team's flag will show at coordinates (0, 0) even though the carrier is still carrying the flag. (#21)
- [x] Teammates can push each other using goliaths (#22)
- [x] Players can respawn without having full health (#23)
- [x] Player can respawn while still having updated a key in the previous 2s (#24)
- [x] (CTF) Prowlers can carry while cloaked (#25)
- [x] Planes flash in their death location for a single frame when respawning (#26)
- [x] (CTF) It is possible to pick up the flag in spec under some conditions
- [x] The server can think you're alive and in spec at the same time
- [x] (CTF) Respawning does not cause flag drops for players with `id != 5` (#27)
- [x] (CTF) Grabbing the flag during intermission breaks a bunch of things
- [x] (CTF) It is possible to grab the flag during intermission (#28)
- [ ] Clients are littered with dead missiles
- [x] Player rank displayed beside the player's name is incorrect. (#29)
- [x] All other players show as having a level of 0
- [x] Whenever a player joins all players see themselves as having a shield (except the player that joined) (#40)

I will try to keep this list up to date as these issues are fixed. If you would like to help with a specific issue it would be best to comment on that issue so that there aren't multiple people working on the same issue.

**Comment by steamroller-airmash** [comment]
Closing as all the important ones seem to be fixed, I'll spin the dead missiles one out into it's own separate issue as it was a preexisting issue.
